version: '3.4'

services:
  api:
    environment: #connection string overriden
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
#      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "ConnectionStrings:DockerSqlServerConn=Server=activitydb,1433;Database=ReactTest;User Id=SA;Password=SwN12345678;Min Pool Size=128;Max Pool Size=5000;Connection Timeout=300;Pooling=true;MultipleActiveResultSets=true"
    depends_on:
        - activitydb
    ports:
        - "8004:80"
     # - "80"
     # - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  activitydb:
    container_name: activitydb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"